// Copyright (c) 2021 Thomas J. Otterson
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

const { expect } = require('chai')

const index = require('operators')

const add = require('operators/add')
const band = require('operators/band')
const bls = require('operators/bls')
const bnot = require('operators/bnot')
const bor = require('operators/bor')
const brs = require('operators/brs')
const burs = require('operators/burs')
const bxor = require('operators/bxor')
const coal = require('operators/coal')
const ceq = require('operators/ceq')
const cne = require('operators/cne')
const cond = require('operators/cond')
const div = require('operators/div')
const eq = require('operators/eq')
const ge = require('operators/ge')
const gt = require('operators/gt')
const land = require('operators/land')
const le = require('operators/le')
const lnot = require('operators/lnot')
const lor = require('operators/lor')
const lt = require('operators/lt')
const mul = require('operators/mul')
const ne = require('operators/ne')
const neg = require('operators/neg')
const opt = require('operators/opt')
const pos = require('operators/pos')
const pow = require('operators/pow')
const prop = require('operators/prop')
const rem = require('operators/rem')
const sub = require('operators/sub')

describe('operators index', () => {
  it('provides all of the exported operators', () => {
    expect(add).to.equal(index.add)
    expect(band).to.equal(index.band)
    expect(bls).to.equal(index.bls)
    expect(bnot).to.equal(index.bnot)
    expect(bor).to.equal(index.bor)
    expect(brs).to.equal(index.brs)
    expect(burs).to.equal(index.burs)
    expect(bxor).to.equal(index.bxor)
    expect(coal).to.equal(index.coal)
    expect(ceq).to.equal(index.ceq)
    expect(cne).to.equal(index.cne)
    expect(cond).to.equal(index.cond)
    expect(div).to.equal(index.div)
    expect(eq).to.equal(index.eq)
    expect(ge).to.equal(index.ge)
    expect(gt).to.equal(index.gt)
    expect(land).to.equal(index.land)
    expect(le).to.equal(index.le)
    expect(lnot).to.equal(index.lnot)
    expect(lor).to.equal(index.lor)
    expect(lt).to.equal(index.lt)
    expect(mul).to.equal(index.mul)
    expect(ne).to.equal(index.ne)
    expect(neg).to.equal(index.neg)
    expect(opt).to.equal(index.opt)
    expect(pos).to.equal(index.pos)
    expect(pow).to.equal(index.pow)
    expect(prop).to.equal(index.prop)
    expect(rem).to.equal(index.rem)
    expect(sub).to.equal(index.sub)
  })
})
